/*********************                                                        */
/** options.cpp
 **
 ** Copyright 2011-2014  New York University and The University of Iowa,
 ** and as below.
 **
 ** This file automatically generated by:
 **
 **     /home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/mkoptions /home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/base_options_template.cpp ../main/options.cpp
 **
 ** for the CVC4 project.
 **/

/* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT ! */
/* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT ! */
/* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT ! */
/* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT ! */
/* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT ! */
/* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT ! */

/* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT ! */
/* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT ! */
/* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT ! */
/* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT ! */
/* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT ! */
/* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT ! */

/* Edit the template file instead.                     */

/*********************                                                        */
/*! \file base_options_template.cpp
 ** \verbatim
 ** Original author: Morgan Deters
 ** Major contributors: none
 ** Minor contributors (to current version): none
 ** This file is part of the CVC4 project.
 ** Copyright (c) 2009-2014  New York University and The University of Iowa
 ** See the file COPYING in the top-level source directory for licensing
 ** information.\endverbatim
 **
 ** \brief Contains code for handling command-line options.
 **
 ** Contains code for handling command-line options
 **/

#include "options/options_holder.h"

namespace CVC4 {


#line 8 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../main/options"
template <> const options::version__option_t::type& Options::operator[](options::version__option_t) const { return d_holder->version; }
#line 8 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../main/options"
template <> bool Options::wasSetByUser(options::version__option_t) const { return d_holder->version__setByUser__; }
#line 12 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../main/options"
template <> const options::help__option_t::type& Options::operator[](options::help__option_t) const { return d_holder->help; }
#line 12 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../main/options"
template <> bool Options::wasSetByUser(options::help__option_t) const { return d_holder->help__setByUser__; }
#line 23 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../main/options"
template <> const options::earlyExit__option_t::type& Options::operator[](options::earlyExit__option_t) const { return d_holder->earlyExit; }
#line 23 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../main/options"
template <> bool Options::wasSetByUser(options::earlyExit__option_t) const { return d_holder->earlyExit__setByUser__; }
#line 27 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../main/options"
template <> const options::threads__option_t::type& Options::operator[](options::threads__option_t) const { return d_holder->threads; }
#line 27 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../main/options"
template <> bool Options::wasSetByUser(options::threads__option_t) const { return d_holder->threads__setByUser__; }
#line 31 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../main/options"
template <> const options::threadStackSize__option_t::type& Options::operator[](options::threadStackSize__option_t) const { return d_holder->threadStackSize; }
#line 31 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../main/options"
template <> bool Options::wasSetByUser(options::threadStackSize__option_t) const { return d_holder->threadStackSize__setByUser__; }
#line 33 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../main/options"
template <> void Options::set(options::threadArgv__option_t, const options::threadArgv__option_t::type& x) { d_holder->threadArgv = x; }
#line 33 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../main/options"
template <> const options::threadArgv__option_t::type& Options::operator[](options::threadArgv__option_t) const { return d_holder->threadArgv; }
#line 33 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../main/options"
template <> bool Options::wasSetByUser(options::threadArgv__option_t) const { return d_holder->threadArgv__setByUser__; }
#line 35 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../main/options"
template <> void Options::set(options::thread_id__option_t, const options::thread_id__option_t::type& x) { d_holder->thread_id = x; }
#line 35 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../main/options"
template <> const options::thread_id__option_t::type& Options::operator[](options::thread_id__option_t) const { return d_holder->thread_id; }
#line 35 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../main/options"
template <> bool Options::wasSetByUser(options::thread_id__option_t) const { return d_holder->thread_id__setByUser__; }
#line 37 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../main/options"
template <> void Options::set(options::sharingFilterByLength__option_t, const options::sharingFilterByLength__option_t::type& x) { d_holder->sharingFilterByLength = x; }
#line 37 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../main/options"
template <> const options::sharingFilterByLength__option_t::type& Options::operator[](options::sharingFilterByLength__option_t) const { return d_holder->sharingFilterByLength; }
#line 37 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../main/options"
template <> bool Options::wasSetByUser(options::sharingFilterByLength__option_t) const { return d_holder->sharingFilterByLength__setByUser__; }
#line 39 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../main/options"
template <> const options::fallbackSequential__option_t::type& Options::operator[](options::fallbackSequential__option_t) const { return d_holder->fallbackSequential; }
#line 39 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../main/options"
template <> bool Options::wasSetByUser(options::fallbackSequential__option_t) const { return d_holder->fallbackSequential__setByUser__; }
#line 41 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../main/options"
template <> const options::incrementalParallel__option_t::type& Options::operator[](options::incrementalParallel__option_t) const { return d_holder->incrementalParallel; }
#line 41 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../main/options"
template <> bool Options::wasSetByUser(options::incrementalParallel__option_t) const { return d_holder->incrementalParallel__setByUser__; }
#line 44 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../main/options"
template <> const options::interactivePrompt__option_t::type& Options::operator[](options::interactivePrompt__option_t) const { return d_holder->interactivePrompt; }
#line 44 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../main/options"
template <> bool Options::wasSetByUser(options::interactivePrompt__option_t) const { return d_holder->interactivePrompt__setByUser__; }
#line 48 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../main/options"
template <> const options::continuedExecution__option_t::type& Options::operator[](options::continuedExecution__option_t) const { return d_holder->continuedExecution; }
#line 48 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../main/options"
template <> bool Options::wasSetByUser(options::continuedExecution__option_t) const { return d_holder->continuedExecution__setByUser__; }
#line 51 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../main/options"
template <> const options::segvSpin__option_t::type& Options::operator[](options::segvSpin__option_t) const { return d_holder->segvSpin; }
#line 51 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../main/options"
template <> bool Options::wasSetByUser(options::segvSpin__option_t) const { return d_holder->segvSpin__setByUser__; }
#line 55 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../main/options"
template <> const options::tearDownIncremental__option_t::type& Options::operator[](options::tearDownIncremental__option_t) const { return d_holder->tearDownIncremental; }
#line 55 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../main/options"
template <> bool Options::wasSetByUser(options::tearDownIncremental__option_t) const { return d_holder->tearDownIncremental__setByUser__; }
#line 58 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../main/options"
template <> const options::waitToJoin__option_t::type& Options::operator[](options::waitToJoin__option_t) const { return d_holder->waitToJoin; }
#line 58 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../main/options"
template <> bool Options::wasSetByUser(options::waitToJoin__option_t) const { return d_holder->waitToJoin__setByUser__; }

#line 24 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/base_options_template.cpp"

namespace options {


#line 8 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../main/options"
struct version__option_t version;
#line 12 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../main/options"
struct help__option_t help;
#line 23 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../main/options"
struct earlyExit__option_t earlyExit;
#line 27 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../main/options"
struct threads__option_t threads;
#line 31 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../main/options"
struct threadStackSize__option_t threadStackSize;
#line 33 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../main/options"
struct threadArgv__option_t threadArgv;
#line 35 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../main/options"
struct thread_id__option_t thread_id;
#line 37 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../main/options"
struct sharingFilterByLength__option_t sharingFilterByLength;
#line 39 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../main/options"
struct fallbackSequential__option_t fallbackSequential;
#line 41 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../main/options"
struct incrementalParallel__option_t incrementalParallel;
#line 44 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../main/options"
struct interactivePrompt__option_t interactivePrompt;
#line 48 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../main/options"
struct continuedExecution__option_t continuedExecution;
#line 51 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../main/options"
struct segvSpin__option_t segvSpin;
#line 55 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../main/options"
struct tearDownIncremental__option_t tearDownIncremental;
#line 58 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../main/options"
struct waitToJoin__option_t waitToJoin;

#line 30 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/base_options_template.cpp"

}/* CVC4::options namespace */

}/* CVC4 namespace */
