/*********************                                                        */
/** options.cpp
 **
 ** Copyright 2011-2014  New York University and The University of Iowa,
 ** and as below.
 **
 ** This file automatically generated by:
 **
 **     /home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/mkoptions /home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/base_options_template.cpp ../smt/options.cpp
 **
 ** for the CVC4 project.
 **/

/* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT ! */
/* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT ! */
/* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT ! */
/* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT ! */
/* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT ! */
/* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT ! */

/* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT ! */
/* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT ! */
/* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT ! */
/* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT ! */
/* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT ! */
/* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT ! */

/* Edit the template file instead.                     */

/*********************                                                        */
/*! \file base_options_template.cpp
 ** \verbatim
 ** Original author: Morgan Deters
 ** Major contributors: none
 ** Minor contributors (to current version): none
 ** This file is part of the CVC4 project.
 ** Copyright (c) 2009-2014  New York University and The University of Iowa
 ** See the file COPYING in the top-level source directory for licensing
 ** information.\endverbatim
 **
 ** \brief Contains code for handling command-line options.
 **
 ** Contains code for handling command-line options
 **/

#include "options/options_holder.h"

namespace CVC4 {


#line 13 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
template <> const options::forceLogic__option_t::type& Options::operator[](options::forceLogic__option_t) const { return d_holder->forceLogic; }
#line 13 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
template <> bool Options::wasSetByUser(options::forceLogic__option_t) const { return d_holder->forceLogic__setByUser__; }
#line 16 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
template <> void Options::set(options::simplificationMode__option_t, const options::simplificationMode__option_t::type& x) { d_holder->simplificationMode = x; }
#line 16 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
template <> const options::simplificationMode__option_t::type& Options::operator[](options::simplificationMode__option_t) const { return d_holder->simplificationMode; }
#line 16 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
template <> bool Options::wasSetByUser(options::simplificationMode__option_t) const { return d_holder->simplificationMode__setByUser__; }
#line 21 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
template <> const options::doStaticLearning__option_t::type& Options::operator[](options::doStaticLearning__option_t) const { return d_holder->doStaticLearning; }
#line 21 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
template <> bool Options::wasSetByUser(options::doStaticLearning__option_t) const { return d_holder->doStaticLearning__setByUser__; }
#line 24 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
template <> const options::expandDefinitions__option_t::type& Options::operator[](options::expandDefinitions__option_t) const { return d_holder->expandDefinitions; }
#line 24 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
template <> bool Options::wasSetByUser(options::expandDefinitions__option_t) const { return d_holder->expandDefinitions__setByUser__; }
#line 26 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
template <> const options::produceModels__option_t::type& Options::operator[](options::produceModels__option_t) const { return d_holder->produceModels; }
#line 26 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
template <> bool Options::wasSetByUser(options::produceModels__option_t) const { return d_holder->produceModels__setByUser__; }
#line 28 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
template <> const options::checkModels__option_t::type& Options::operator[](options::checkModels__option_t) const { return d_holder->checkModels; }
#line 28 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
template <> bool Options::wasSetByUser(options::checkModels__option_t) const { return d_holder->checkModels__setByUser__; }
#line 30 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
template <> const options::dumpModels__option_t::type& Options::operator[](options::dumpModels__option_t) const { return d_holder->dumpModels; }
#line 30 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
template <> bool Options::wasSetByUser(options::dumpModels__option_t) const { return d_holder->dumpModels__setByUser__; }
#line 32 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
template <> const options::proof__option_t::type& Options::operator[](options::proof__option_t) const { return d_holder->proof; }
#line 32 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
template <> bool Options::wasSetByUser(options::proof__option_t) const { return d_holder->proof__setByUser__; }
#line 34 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
template <> const options::checkProofs__option_t::type& Options::operator[](options::checkProofs__option_t) const { return d_holder->checkProofs; }
#line 34 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
template <> bool Options::wasSetByUser(options::checkProofs__option_t) const { return d_holder->checkProofs__setByUser__; }
#line 36 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
template <> const options::dumpProofs__option_t::type& Options::operator[](options::dumpProofs__option_t) const { return d_holder->dumpProofs; }
#line 36 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
template <> bool Options::wasSetByUser(options::dumpProofs__option_t) const { return d_holder->dumpProofs__setByUser__; }
#line 38 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
template <> const options::dumpInstantiations__option_t::type& Options::operator[](options::dumpInstantiations__option_t) const { return d_holder->dumpInstantiations; }
#line 38 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
template <> bool Options::wasSetByUser(options::dumpInstantiations__option_t) const { return d_holder->dumpInstantiations__setByUser__; }
#line 41 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
template <> const options::unsatCores__option_t::type& Options::operator[](options::unsatCores__option_t) const { return d_holder->unsatCores; }
#line 41 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
template <> bool Options::wasSetByUser(options::unsatCores__option_t) const { return d_holder->unsatCores__setByUser__; }
#line 43 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
template <> const options::produceAssignments__option_t::type& Options::operator[](options::produceAssignments__option_t) const { return d_holder->produceAssignments; }
#line 43 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
template <> bool Options::wasSetByUser(options::produceAssignments__option_t) const { return d_holder->produceAssignments__setByUser__; }
#line 48 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
template <> void Options::set(options::interactive__option_t, const options::interactive__option_t::type& x) { d_holder->interactive = x; }
#line 48 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
template <> const options::interactive__option_t::type& Options::operator[](options::interactive__option_t) const { return d_holder->interactive; }
#line 48 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
template <> bool Options::wasSetByUser(options::interactive__option_t) const { return d_holder->interactive__setByUser__; }
#line 51 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
template <> void Options::set(options::doITESimp__option_t, const options::doITESimp__option_t::type& x) { d_holder->doITESimp = x; }
#line 51 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
template <> const options::doITESimp__option_t::type& Options::operator[](options::doITESimp__option_t) const { return d_holder->doITESimp; }
#line 51 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
template <> bool Options::wasSetByUser(options::doITESimp__option_t) const { return d_holder->doITESimp__setByUser__; }
#line 54 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
template <> void Options::set(options::doITESimpOnRepeat__option_t, const options::doITESimpOnRepeat__option_t::type& x) { d_holder->doITESimpOnRepeat = x; }
#line 54 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
template <> const options::doITESimpOnRepeat__option_t::type& Options::operator[](options::doITESimpOnRepeat__option_t) const { return d_holder->doITESimpOnRepeat; }
#line 54 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
template <> bool Options::wasSetByUser(options::doITESimpOnRepeat__option_t) const { return d_holder->doITESimpOnRepeat__setByUser__; }
#line 57 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
template <> void Options::set(options::simplifyWithCareEnabled__option_t, const options::simplifyWithCareEnabled__option_t::type& x) { d_holder->simplifyWithCareEnabled = x; }
#line 57 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
template <> const options::simplifyWithCareEnabled__option_t::type& Options::operator[](options::simplifyWithCareEnabled__option_t) const { return d_holder->simplifyWithCareEnabled; }
#line 57 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
template <> bool Options::wasSetByUser(options::simplifyWithCareEnabled__option_t) const { return d_holder->simplifyWithCareEnabled__setByUser__; }
#line 60 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
template <> void Options::set(options::compressItes__option_t, const options::compressItes__option_t::type& x) { d_holder->compressItes = x; }
#line 60 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
template <> const options::compressItes__option_t::type& Options::operator[](options::compressItes__option_t) const { return d_holder->compressItes; }
#line 60 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
template <> bool Options::wasSetByUser(options::compressItes__option_t) const { return d_holder->compressItes__setByUser__; }
#line 63 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
template <> void Options::set(options::unconstrainedSimp__option_t, const options::unconstrainedSimp__option_t::type& x) { d_holder->unconstrainedSimp = x; }
#line 63 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
template <> const options::unconstrainedSimp__option_t::type& Options::operator[](options::unconstrainedSimp__option_t) const { return d_holder->unconstrainedSimp; }
#line 63 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
template <> bool Options::wasSetByUser(options::unconstrainedSimp__option_t) const { return d_holder->unconstrainedSimp__setByUser__; }
#line 66 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
template <> void Options::set(options::repeatSimp__option_t, const options::repeatSimp__option_t::type& x) { d_holder->repeatSimp = x; }
#line 66 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
template <> const options::repeatSimp__option_t::type& Options::operator[](options::repeatSimp__option_t) const { return d_holder->repeatSimp; }
#line 66 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
template <> bool Options::wasSetByUser(options::repeatSimp__option_t) const { return d_holder->repeatSimp__setByUser__; }
#line 69 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
template <> const options::zombieHuntThreshold__option_t::type& Options::operator[](options::zombieHuntThreshold__option_t) const { return d_holder->zombieHuntThreshold; }
#line 69 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
template <> bool Options::wasSetByUser(options::zombieHuntThreshold__option_t) const { return d_holder->zombieHuntThreshold__setByUser__; }
#line 72 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
template <> void Options::set(options::sortInference__option_t, const options::sortInference__option_t::type& x) { d_holder->sortInference = x; }
#line 72 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
template <> const options::sortInference__option_t::type& Options::operator[](options::sortInference__option_t) const { return d_holder->sortInference; }
#line 72 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
template <> bool Options::wasSetByUser(options::sortInference__option_t) const { return d_holder->sortInference__setByUser__; }
#line 75 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
template <> const options::incrementalSolving__option_t::type& Options::operator[](options::incrementalSolving__option_t) const { return d_holder->incrementalSolving; }
#line 75 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
template <> bool Options::wasSetByUser(options::incrementalSolving__option_t) const { return d_holder->incrementalSolving__setByUser__; }
#line 78 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
template <> const options::abstractValues__option_t::type& Options::operator[](options::abstractValues__option_t) const { return d_holder->abstractValues; }
#line 78 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
template <> bool Options::wasSetByUser(options::abstractValues__option_t) const { return d_holder->abstractValues__setByUser__; }
#line 80 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
template <> const options::modelUninterpDtEnum__option_t::type& Options::operator[](options::modelUninterpDtEnum__option_t) const { return d_holder->modelUninterpDtEnum; }
#line 80 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
template <> bool Options::wasSetByUser(options::modelUninterpDtEnum__option_t) const { return d_holder->modelUninterpDtEnum__setByUser__; }
#line 88 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
template <> const options::cumulativeMillisecondLimit__option_t::type& Options::operator[](options::cumulativeMillisecondLimit__option_t) const { return d_holder->cumulativeMillisecondLimit; }
#line 88 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
template <> bool Options::wasSetByUser(options::cumulativeMillisecondLimit__option_t) const { return d_holder->cumulativeMillisecondLimit__setByUser__; }
#line 90 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
template <> const options::perCallMillisecondLimit__option_t::type& Options::operator[](options::perCallMillisecondLimit__option_t) const { return d_holder->perCallMillisecondLimit; }
#line 90 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
template <> bool Options::wasSetByUser(options::perCallMillisecondLimit__option_t) const { return d_holder->perCallMillisecondLimit__setByUser__; }
#line 92 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
template <> const options::cumulativeResourceLimit__option_t::type& Options::operator[](options::cumulativeResourceLimit__option_t) const { return d_holder->cumulativeResourceLimit; }
#line 92 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
template <> bool Options::wasSetByUser(options::cumulativeResourceLimit__option_t) const { return d_holder->cumulativeResourceLimit__setByUser__; }
#line 94 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
template <> const options::perCallResourceLimit__option_t::type& Options::operator[](options::perCallResourceLimit__option_t) const { return d_holder->perCallResourceLimit; }
#line 94 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
template <> bool Options::wasSetByUser(options::perCallResourceLimit__option_t) const { return d_holder->perCallResourceLimit__setByUser__; }
#line 97 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
template <> const options::rewriteApplyToConst__option_t::type& Options::operator[](options::rewriteApplyToConst__option_t) const { return d_holder->rewriteApplyToConst; }
#line 97 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
template <> bool Options::wasSetByUser(options::rewriteApplyToConst__option_t) const { return d_holder->rewriteApplyToConst__setByUser__; }
#line 101 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
template <> const options::replayFilename__option_t::type& Options::operator[](options::replayFilename__option_t) const { return d_holder->replayFilename; }
#line 101 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
template <> bool Options::wasSetByUser(options::replayFilename__option_t) const { return d_holder->replayFilename__setByUser__; }
#line 103 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
template <> const options::replayLog__option_t::type& Options::operator[](options::replayLog__option_t) const { return d_holder->replayLog; }
#line 103 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
template <> bool Options::wasSetByUser(options::replayLog__option_t) const { return d_holder->replayLog__setByUser__; }
#line 105 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
template <> void Options::set(options::replayStream__option_t, const options::replayStream__option_t::type& x) { d_holder->replayStream = x; }
#line 105 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
template <> const options::replayStream__option_t::type& Options::operator[](options::replayStream__option_t) const { return d_holder->replayStream; }
#line 105 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
template <> bool Options::wasSetByUser(options::replayStream__option_t) const { return d_holder->replayStream__setByUser__; }
#line 108 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
template <> void Options::set(options::lemmaInputChannel__option_t, const options::lemmaInputChannel__option_t::type& x) { d_holder->lemmaInputChannel = x; }
#line 108 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
template <> const options::lemmaInputChannel__option_t::type& Options::operator[](options::lemmaInputChannel__option_t) const { return d_holder->lemmaInputChannel; }
#line 108 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
template <> bool Options::wasSetByUser(options::lemmaInputChannel__option_t) const { return d_holder->lemmaInputChannel__setByUser__; }
#line 110 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
template <> void Options::set(options::lemmaOutputChannel__option_t, const options::lemmaOutputChannel__option_t::type& x) { d_holder->lemmaOutputChannel = x; }
#line 110 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
template <> const options::lemmaOutputChannel__option_t::type& Options::operator[](options::lemmaOutputChannel__option_t) const { return d_holder->lemmaOutputChannel; }
#line 110 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
template <> bool Options::wasSetByUser(options::lemmaOutputChannel__option_t) const { return d_holder->lemmaOutputChannel__setByUser__; }
#line 113 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
template <> const options::forceNoLimitCpuWhileDump__option_t::type& Options::operator[](options::forceNoLimitCpuWhileDump__option_t) const { return d_holder->forceNoLimitCpuWhileDump; }
#line 113 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
template <> bool Options::wasSetByUser(options::forceNoLimitCpuWhileDump__option_t) const { return d_holder->forceNoLimitCpuWhileDump__setByUser__; }

#line 24 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/base_options_template.cpp"

namespace options {


#line 13 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
struct forceLogic__option_t forceLogic;
#line 16 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
struct simplificationMode__option_t simplificationMode;
#line 21 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
struct doStaticLearning__option_t doStaticLearning;
#line 24 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
struct expandDefinitions__option_t expandDefinitions;
#line 26 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
struct produceModels__option_t produceModels;
#line 28 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
struct checkModels__option_t checkModels;
#line 30 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
struct dumpModels__option_t dumpModels;
#line 32 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
struct proof__option_t proof;
#line 34 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
struct checkProofs__option_t checkProofs;
#line 36 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
struct dumpProofs__option_t dumpProofs;
#line 38 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
struct dumpInstantiations__option_t dumpInstantiations;
#line 41 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
struct unsatCores__option_t unsatCores;
#line 43 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
struct produceAssignments__option_t produceAssignments;
#line 48 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
struct interactive__option_t interactive;
#line 51 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
struct doITESimp__option_t doITESimp;
#line 54 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
struct doITESimpOnRepeat__option_t doITESimpOnRepeat;
#line 57 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
struct simplifyWithCareEnabled__option_t simplifyWithCareEnabled;
#line 60 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
struct compressItes__option_t compressItes;
#line 63 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
struct unconstrainedSimp__option_t unconstrainedSimp;
#line 66 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
struct repeatSimp__option_t repeatSimp;
#line 69 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
struct zombieHuntThreshold__option_t zombieHuntThreshold;
#line 72 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
struct sortInference__option_t sortInference;
#line 75 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
struct incrementalSolving__option_t incrementalSolving;
#line 78 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
struct abstractValues__option_t abstractValues;
#line 80 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
struct modelUninterpDtEnum__option_t modelUninterpDtEnum;
#line 88 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
struct cumulativeMillisecondLimit__option_t cumulativeMillisecondLimit;
#line 90 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
struct perCallMillisecondLimit__option_t perCallMillisecondLimit;
#line 92 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
struct cumulativeResourceLimit__option_t cumulativeResourceLimit;
#line 94 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
struct perCallResourceLimit__option_t perCallResourceLimit;
#line 97 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
struct rewriteApplyToConst__option_t rewriteApplyToConst;
#line 101 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
struct replayFilename__option_t replayFilename;
#line 103 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
struct replayLog__option_t replayLog;
#line 105 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
struct replayStream__option_t replayStream;
#line 108 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
struct lemmaInputChannel__option_t lemmaInputChannel;
#line 110 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
struct lemmaOutputChannel__option_t lemmaOutputChannel;
#line 113 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../smt/options"
struct forceNoLimitCpuWhileDump__option_t forceNoLimitCpuWhileDump;

#line 30 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/base_options_template.cpp"

}/* CVC4::options namespace */

}/* CVC4 namespace */
