/*************************************************************/
/* Automatically generated by './mkconfig.sh': do note edit! */
/*************************************************************/
#define LGL_OS "Linux compute-0-1.local 2.6.32-431.11.2.el6.x86_64 x86_64"
#define LGL_COMPILED "Wed Jun 24 13:42:24 IST 2015"
#define LGL_RELEASED "Tue May 26 11:34:00 CEST 2015"
#define LGL_VERSION "azd"
#define LGL_ID "0d997521ad2e7d4e94f5d74a4665455b91309b62"
