/*********************                                                        */
/** options.cpp
 **
 ** Copyright 2011-2014  New York University and The University of Iowa,
 ** and as below.
 **
 ** This file automatically generated by:
 **
 **     /home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/mkoptions /home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/base_options_template.cpp ../theory/strings/options.cpp
 **
 ** for the CVC4 project.
 **/

/* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT ! */
/* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT ! */
/* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT ! */
/* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT ! */
/* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT ! */
/* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT ! */

/* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT ! */
/* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT ! */
/* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT ! */
/* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT ! */
/* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT ! */
/* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT ! */

/* Edit the template file instead.                     */

/*********************                                                        */
/*! \file base_options_template.cpp
 ** \verbatim
 ** Original author: Morgan Deters
 ** Major contributors: none
 ** Minor contributors (to current version): none
 ** This file is part of the CVC4 project.
 ** Copyright (c) 2009-2014  New York University and The University of Iowa
 ** See the file COPYING in the top-level source directory for licensing
 ** information.\endverbatim
 **
 ** \brief Contains code for handling command-line options.
 **
 ** Contains code for handling command-line options
 **/

#include "options/options_holder.h"

namespace CVC4 {


#line 8 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/strings/options"
template <> void Options::set(options::stringExp__option_t, const options::stringExp__option_t::type& x) { d_holder->stringExp = x; }
#line 8 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/strings/options"
template <> const options::stringExp__option_t::type& Options::operator[](options::stringExp__option_t) const { return d_holder->stringExp; }
#line 8 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/strings/options"
template <> bool Options::wasSetByUser(options::stringExp__option_t) const { return d_holder->stringExp__setByUser__; }
#line 11 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/strings/options"
template <> const options::stringLB__option_t::type& Options::operator[](options::stringLB__option_t) const { return d_holder->stringLB; }
#line 11 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/strings/options"
template <> bool Options::wasSetByUser(options::stringLB__option_t) const { return d_holder->stringLB__setByUser__; }
#line 14 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/strings/options"
template <> void Options::set(options::stringFMF__option_t, const options::stringFMF__option_t::type& x) { d_holder->stringFMF = x; }
#line 14 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/strings/options"
template <> const options::stringFMF__option_t::type& Options::operator[](options::stringFMF__option_t) const { return d_holder->stringFMF; }
#line 14 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/strings/options"
template <> bool Options::wasSetByUser(options::stringFMF__option_t) const { return d_holder->stringFMF__setByUser__; }
#line 17 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/strings/options"
template <> const options::stringEIT__option_t::type& Options::operator[](options::stringEIT__option_t) const { return d_holder->stringEIT; }
#line 17 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/strings/options"
template <> bool Options::wasSetByUser(options::stringEIT__option_t) const { return d_holder->stringEIT__setByUser__; }
#line 20 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/strings/options"
template <> const options::stringOpt1__option_t::type& Options::operator[](options::stringOpt1__option_t) const { return d_holder->stringOpt1; }
#line 20 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/strings/options"
template <> bool Options::wasSetByUser(options::stringOpt1__option_t) const { return d_holder->stringOpt1__setByUser__; }
#line 23 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/strings/options"
template <> const options::stringOpt2__option_t::type& Options::operator[](options::stringOpt2__option_t) const { return d_holder->stringOpt2; }
#line 23 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/strings/options"
template <> bool Options::wasSetByUser(options::stringOpt2__option_t) const { return d_holder->stringOpt2__setByUser__; }
#line 26 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/strings/options"
template <> const options::stringCharCardinality__option_t::type& Options::operator[](options::stringCharCardinality__option_t) const { return d_holder->stringCharCardinality; }
#line 26 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/strings/options"
template <> bool Options::wasSetByUser(options::stringCharCardinality__option_t) const { return d_holder->stringCharCardinality__setByUser__; }

#line 24 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/base_options_template.cpp"

namespace options {


#line 8 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/strings/options"
struct stringExp__option_t stringExp;
#line 11 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/strings/options"
struct stringLB__option_t stringLB;
#line 14 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/strings/options"
struct stringFMF__option_t stringFMF;
#line 17 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/strings/options"
struct stringEIT__option_t stringEIT;
#line 20 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/strings/options"
struct stringOpt1__option_t stringOpt1;
#line 23 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/strings/options"
struct stringOpt2__option_t stringOpt2;
#line 26 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/strings/options"
struct stringCharCardinality__option_t stringCharCardinality;

#line 30 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/base_options_template.cpp"

}/* CVC4::options namespace */

}/* CVC4 namespace */
