/**********************************************************/
/* Automatically generated by './mkconfig': do note edit! */
/**********************************************************/
#define BTOR_CC "gcc (GCC) 4.9.2 20150304 (prerelease)"
#define BTOR_CXX "g++"
#define BTOR_CFLAGS "-W -Wall -Wextra -Wredundant-decls -fPIC -O3 -DNDEBUG -DNBTORLOG -DBTOR_USE_PICOSAT -DBTOR_USE_LINGELING -DBTOR_ENABLE_BETA_REDUCTION_PROBING -DBTOR_USE_MINISAT"
#define BTOR_OS "Linux pino 3.19.2-1-ARCH x86_64"
#define BTOR_COMPILED "Tue May 26 11:32:27 CEST 2015"
#define BTOR_RELEASED "Tue May 26 11:32:27 CEST 2015"
#define BTOR_VERSION "2.0.7"
#define BTOR_ID "3d69b22259f8d7388b94e781b1b5994ee0d55e81"
