/*********************                                                        */
/** options.cpp
 **
 ** Copyright 2011-2014  New York University and The University of Iowa,
 ** and as below.
 **
 ** This file automatically generated by:
 **
 **     /home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/mkoptions /home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/base_options_template.cpp ../theory/arith/options.cpp
 **
 ** for the CVC4 project.
 **/

/* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT ! */
/* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT ! */
/* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT ! */
/* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT ! */
/* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT ! */
/* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT ! */

/* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT ! */
/* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT ! */
/* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT ! */
/* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT ! */
/* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT ! */
/* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT ! */

/* Edit the template file instead.                     */

/*********************                                                        */
/*! \file base_options_template.cpp
 ** \verbatim
 ** Original author: Morgan Deters
 ** Major contributors: none
 ** Minor contributors (to current version): none
 ** This file is part of the CVC4 project.
 ** Copyright (c) 2009-2014  New York University and The University of Iowa
 ** See the file COPYING in the top-level source directory for licensing
 ** information.\endverbatim
 **
 ** \brief Contains code for handling command-line options.
 **
 ** Contains code for handling command-line options
 **/

#include "options/options_holder.h"

namespace CVC4 {


#line 8 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> const options::arithUnateLemmaMode__option_t::type& Options::operator[](options::arithUnateLemmaMode__option_t) const { return d_holder->arithUnateLemmaMode; }
#line 8 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> bool Options::wasSetByUser(options::arithUnateLemmaMode__option_t) const { return d_holder->arithUnateLemmaMode__setByUser__; }
#line 11 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> const options::arithPropagationMode__option_t::type& Options::operator[](options::arithPropagationMode__option_t) const { return d_holder->arithPropagationMode; }
#line 11 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> bool Options::wasSetByUser(options::arithPropagationMode__option_t) const { return d_holder->arithPropagationMode__setByUser__; }
#line 18 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> void Options::set(options::arithHeuristicPivots__option_t, const options::arithHeuristicPivots__option_t::type& x) { d_holder->arithHeuristicPivots = x; }
#line 18 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> const options::arithHeuristicPivots__option_t::type& Options::operator[](options::arithHeuristicPivots__option_t) const { return d_holder->arithHeuristicPivots; }
#line 18 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> bool Options::wasSetByUser(options::arithHeuristicPivots__option_t) const { return d_holder->arithHeuristicPivots__setByUser__; }
#line 25 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> void Options::set(options::arithStandardCheckVarOrderPivots__option_t, const options::arithStandardCheckVarOrderPivots__option_t::type& x) { d_holder->arithStandardCheckVarOrderPivots = x; }
#line 25 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> const options::arithStandardCheckVarOrderPivots__option_t::type& Options::operator[](options::arithStandardCheckVarOrderPivots__option_t) const { return d_holder->arithStandardCheckVarOrderPivots; }
#line 25 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> bool Options::wasSetByUser(options::arithStandardCheckVarOrderPivots__option_t) const { return d_holder->arithStandardCheckVarOrderPivots__setByUser__; }
#line 28 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> const options::arithErrorSelectionRule__option_t::type& Options::operator[](options::arithErrorSelectionRule__option_t) const { return d_holder->arithErrorSelectionRule; }
#line 28 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> bool Options::wasSetByUser(options::arithErrorSelectionRule__option_t) const { return d_holder->arithErrorSelectionRule__setByUser__; }
#line 32 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> const options::arithSimplexCheckPeriod__option_t::type& Options::operator[](options::arithSimplexCheckPeriod__option_t) const { return d_holder->arithSimplexCheckPeriod; }
#line 32 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> bool Options::wasSetByUser(options::arithSimplexCheckPeriod__option_t) const { return d_holder->arithSimplexCheckPeriod__setByUser__; }
#line 39 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> void Options::set(options::arithPivotThreshold__option_t, const options::arithPivotThreshold__option_t::type& x) { d_holder->arithPivotThreshold = x; }
#line 39 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> const options::arithPivotThreshold__option_t::type& Options::operator[](options::arithPivotThreshold__option_t) const { return d_holder->arithPivotThreshold; }
#line 39 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> bool Options::wasSetByUser(options::arithPivotThreshold__option_t) const { return d_holder->arithPivotThreshold__setByUser__; }
#line 42 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> const options::arithPropagateMaxLength__option_t::type& Options::operator[](options::arithPropagateMaxLength__option_t) const { return d_holder->arithPropagateMaxLength; }
#line 42 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> bool Options::wasSetByUser(options::arithPropagateMaxLength__option_t) const { return d_holder->arithPropagateMaxLength__setByUser__; }
#line 45 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> const options::arithDioSolver__option_t::type& Options::operator[](options::arithDioSolver__option_t) const { return d_holder->arithDioSolver; }
#line 45 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> bool Options::wasSetByUser(options::arithDioSolver__option_t) const { return d_holder->arithDioSolver__setByUser__; }
#line 50 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> void Options::set(options::arithRewriteEq__option_t, const options::arithRewriteEq__option_t::type& x) { d_holder->arithRewriteEq = x; }
#line 50 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> const options::arithRewriteEq__option_t::type& Options::operator[](options::arithRewriteEq__option_t) const { return d_holder->arithRewriteEq; }
#line 50 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> bool Options::wasSetByUser(options::arithRewriteEq__option_t) const { return d_holder->arithRewriteEq__setByUser__; }
#line 55 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> const options::arithMLTrick__option_t::type& Options::operator[](options::arithMLTrick__option_t) const { return d_holder->arithMLTrick; }
#line 55 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> bool Options::wasSetByUser(options::arithMLTrick__option_t) const { return d_holder->arithMLTrick__setByUser__; }
#line 59 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> const options::arithMLTrickSubstitutions__option_t::type& Options::operator[](options::arithMLTrickSubstitutions__option_t) const { return d_holder->arithMLTrickSubstitutions; }
#line 59 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> bool Options::wasSetByUser(options::arithMLTrickSubstitutions__option_t) const { return d_holder->arithMLTrickSubstitutions__setByUser__; }
#line 62 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> void Options::set(options::doCutAllBounded__option_t, const options::doCutAllBounded__option_t::type& x) { d_holder->doCutAllBounded = x; }
#line 62 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> const options::doCutAllBounded__option_t::type& Options::operator[](options::doCutAllBounded__option_t) const { return d_holder->doCutAllBounded; }
#line 62 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> bool Options::wasSetByUser(options::doCutAllBounded__option_t) const { return d_holder->doCutAllBounded__setByUser__; }
#line 66 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> const options::maxCutsInContext__option_t::type& Options::operator[](options::maxCutsInContext__option_t) const { return d_holder->maxCutsInContext; }
#line 66 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> bool Options::wasSetByUser(options::maxCutsInContext__option_t) const { return d_holder->maxCutsInContext__setByUser__; }
#line 69 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> const options::revertArithModels__option_t::type& Options::operator[](options::revertArithModels__option_t) const { return d_holder->revertArithModels; }
#line 69 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> bool Options::wasSetByUser(options::revertArithModels__option_t) const { return d_holder->revertArithModels__setByUser__; }
#line 72 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> void Options::set(options::havePenalties__option_t, const options::havePenalties__option_t::type& x) { d_holder->havePenalties = x; }
#line 72 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> const options::havePenalties__option_t::type& Options::operator[](options::havePenalties__option_t) const { return d_holder->havePenalties; }
#line 72 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> bool Options::wasSetByUser(options::havePenalties__option_t) const { return d_holder->havePenalties__setByUser__; }
#line 76 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> void Options::set(options::useFC__option_t, const options::useFC__option_t::type& x) { d_holder->useFC = x; }
#line 76 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> const options::useFC__option_t::type& Options::operator[](options::useFC__option_t) const { return d_holder->useFC; }
#line 76 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> bool Options::wasSetByUser(options::useFC__option_t) const { return d_holder->useFC__setByUser__; }
#line 79 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> void Options::set(options::useSOI__option_t, const options::useSOI__option_t::type& x) { d_holder->useSOI = x; }
#line 79 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> const options::useSOI__option_t::type& Options::operator[](options::useSOI__option_t) const { return d_holder->useSOI; }
#line 79 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> bool Options::wasSetByUser(options::useSOI__option_t) const { return d_holder->useSOI__setByUser__; }
#line 82 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> void Options::set(options::restrictedPivots__option_t, const options::restrictedPivots__option_t::type& x) { d_holder->restrictedPivots = x; }
#line 82 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> const options::restrictedPivots__option_t::type& Options::operator[](options::restrictedPivots__option_t) const { return d_holder->restrictedPivots; }
#line 82 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> bool Options::wasSetByUser(options::restrictedPivots__option_t) const { return d_holder->restrictedPivots__setByUser__; }
#line 85 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> void Options::set(options::collectPivots__option_t, const options::collectPivots__option_t::type& x) { d_holder->collectPivots = x; }
#line 85 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> const options::collectPivots__option_t::type& Options::operator[](options::collectPivots__option_t) const { return d_holder->collectPivots; }
#line 85 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> bool Options::wasSetByUser(options::collectPivots__option_t) const { return d_holder->collectPivots__setByUser__; }
#line 88 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> void Options::set(options::useApprox__option_t, const options::useApprox__option_t::type& x) { d_holder->useApprox = x; }
#line 88 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> const options::useApprox__option_t::type& Options::operator[](options::useApprox__option_t) const { return d_holder->useApprox; }
#line 88 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> bool Options::wasSetByUser(options::useApprox__option_t) const { return d_holder->useApprox__setByUser__; }
#line 91 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> void Options::set(options::maxApproxDepth__option_t, const options::maxApproxDepth__option_t::type& x) { d_holder->maxApproxDepth = x; }
#line 91 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> const options::maxApproxDepth__option_t::type& Options::operator[](options::maxApproxDepth__option_t) const { return d_holder->maxApproxDepth; }
#line 91 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> bool Options::wasSetByUser(options::maxApproxDepth__option_t) const { return d_holder->maxApproxDepth__setByUser__; }
#line 94 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> void Options::set(options::exportDioDecompositions__option_t, const options::exportDioDecompositions__option_t::type& x) { d_holder->exportDioDecompositions = x; }
#line 94 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> const options::exportDioDecompositions__option_t::type& Options::operator[](options::exportDioDecompositions__option_t) const { return d_holder->exportDioDecompositions; }
#line 94 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> bool Options::wasSetByUser(options::exportDioDecompositions__option_t) const { return d_holder->exportDioDecompositions__setByUser__; }
#line 97 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> void Options::set(options::newProp__option_t, const options::newProp__option_t::type& x) { d_holder->newProp = x; }
#line 97 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> const options::newProp__option_t::type& Options::operator[](options::newProp__option_t) const { return d_holder->newProp; }
#line 97 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> bool Options::wasSetByUser(options::newProp__option_t) const { return d_holder->newProp__setByUser__; }
#line 100 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> void Options::set(options::arithPropAsLemmaLength__option_t, const options::arithPropAsLemmaLength__option_t::type& x) { d_holder->arithPropAsLemmaLength = x; }
#line 100 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> const options::arithPropAsLemmaLength__option_t::type& Options::operator[](options::arithPropAsLemmaLength__option_t) const { return d_holder->arithPropAsLemmaLength; }
#line 100 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> bool Options::wasSetByUser(options::arithPropAsLemmaLength__option_t) const { return d_holder->arithPropAsLemmaLength__setByUser__; }
#line 103 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> void Options::set(options::soiQuickExplain__option_t, const options::soiQuickExplain__option_t::type& x) { d_holder->soiQuickExplain = x; }
#line 103 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> const options::soiQuickExplain__option_t::type& Options::operator[](options::soiQuickExplain__option_t) const { return d_holder->soiQuickExplain; }
#line 103 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> bool Options::wasSetByUser(options::soiQuickExplain__option_t) const { return d_holder->soiQuickExplain__setByUser__; }
#line 106 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> void Options::set(options::rewriteDivk__option_t, const options::rewriteDivk__option_t::type& x) { d_holder->rewriteDivk = x; }
#line 106 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> const options::rewriteDivk__option_t::type& Options::operator[](options::rewriteDivk__option_t) const { return d_holder->rewriteDivk; }
#line 106 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> bool Options::wasSetByUser(options::rewriteDivk__option_t) const { return d_holder->rewriteDivk__setByUser__; }
#line 109 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> const options::trySolveIntStandardEffort__option_t::type& Options::operator[](options::trySolveIntStandardEffort__option_t) const { return d_holder->trySolveIntStandardEffort; }
#line 109 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> bool Options::wasSetByUser(options::trySolveIntStandardEffort__option_t) const { return d_holder->trySolveIntStandardEffort__setByUser__; }
#line 112 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> const options::replayFailureLemma__option_t::type& Options::operator[](options::replayFailureLemma__option_t) const { return d_holder->replayFailureLemma; }
#line 112 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> bool Options::wasSetByUser(options::replayFailureLemma__option_t) const { return d_holder->replayFailureLemma__setByUser__; }
#line 115 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> const options::dioSolverTurns__option_t::type& Options::operator[](options::dioSolverTurns__option_t) const { return d_holder->dioSolverTurns; }
#line 115 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> bool Options::wasSetByUser(options::dioSolverTurns__option_t) const { return d_holder->dioSolverTurns__setByUser__; }
#line 118 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> const options::rrTurns__option_t::type& Options::operator[](options::rrTurns__option_t) const { return d_holder->rrTurns; }
#line 118 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> bool Options::wasSetByUser(options::rrTurns__option_t) const { return d_holder->rrTurns__setByUser__; }
#line 121 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> const options::dioRepeat__option_t::type& Options::operator[](options::dioRepeat__option_t) const { return d_holder->dioRepeat; }
#line 121 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> bool Options::wasSetByUser(options::dioRepeat__option_t) const { return d_holder->dioRepeat__setByUser__; }
#line 124 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> const options::replayEarlyCloseDepths__option_t::type& Options::operator[](options::replayEarlyCloseDepths__option_t) const { return d_holder->replayEarlyCloseDepths; }
#line 124 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> bool Options::wasSetByUser(options::replayEarlyCloseDepths__option_t) const { return d_holder->replayEarlyCloseDepths__setByUser__; }
#line 127 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> const options::replayFailurePenalty__option_t::type& Options::operator[](options::replayFailurePenalty__option_t) const { return d_holder->replayFailurePenalty; }
#line 127 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> bool Options::wasSetByUser(options::replayFailurePenalty__option_t) const { return d_holder->replayFailurePenalty__setByUser__; }
#line 130 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> const options::replayNumericFailurePenalty__option_t::type& Options::operator[](options::replayNumericFailurePenalty__option_t) const { return d_holder->replayNumericFailurePenalty; }
#line 130 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> bool Options::wasSetByUser(options::replayNumericFailurePenalty__option_t) const { return d_holder->replayNumericFailurePenalty__setByUser__; }
#line 133 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> const options::replayRejectCutSize__option_t::type& Options::operator[](options::replayRejectCutSize__option_t) const { return d_holder->replayRejectCutSize; }
#line 133 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> bool Options::wasSetByUser(options::replayRejectCutSize__option_t) const { return d_holder->replayRejectCutSize__setByUser__; }
#line 136 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> const options::lemmaRejectCutSize__option_t::type& Options::operator[](options::lemmaRejectCutSize__option_t) const { return d_holder->lemmaRejectCutSize; }
#line 136 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> bool Options::wasSetByUser(options::lemmaRejectCutSize__option_t) const { return d_holder->lemmaRejectCutSize__setByUser__; }
#line 139 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> const options::soiApproxMajorFailure__option_t::type& Options::operator[](options::soiApproxMajorFailure__option_t) const { return d_holder->soiApproxMajorFailure; }
#line 139 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> bool Options::wasSetByUser(options::soiApproxMajorFailure__option_t) const { return d_holder->soiApproxMajorFailure__setByUser__; }
#line 142 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> const options::soiApproxMajorFailurePen__option_t::type& Options::operator[](options::soiApproxMajorFailurePen__option_t) const { return d_holder->soiApproxMajorFailurePen; }
#line 142 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> bool Options::wasSetByUser(options::soiApproxMajorFailurePen__option_t) const { return d_holder->soiApproxMajorFailurePen__setByUser__; }
#line 145 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> const options::soiApproxMinorFailure__option_t::type& Options::operator[](options::soiApproxMinorFailure__option_t) const { return d_holder->soiApproxMinorFailure; }
#line 145 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> bool Options::wasSetByUser(options::soiApproxMinorFailure__option_t) const { return d_holder->soiApproxMinorFailure__setByUser__; }
#line 148 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> const options::soiApproxMinorFailurePen__option_t::type& Options::operator[](options::soiApproxMinorFailurePen__option_t) const { return d_holder->soiApproxMinorFailurePen; }
#line 148 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> bool Options::wasSetByUser(options::soiApproxMinorFailurePen__option_t) const { return d_holder->soiApproxMinorFailurePen__setByUser__; }
#line 151 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> const options::ppAssertMaxSubSize__option_t::type& Options::operator[](options::ppAssertMaxSubSize__option_t) const { return d_holder->ppAssertMaxSubSize; }
#line 151 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> bool Options::wasSetByUser(options::ppAssertMaxSubSize__option_t) const { return d_holder->ppAssertMaxSubSize__setByUser__; }
#line 154 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> const options::maxReplayTree__option_t::type& Options::operator[](options::maxReplayTree__option_t) const { return d_holder->maxReplayTree; }
#line 154 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> bool Options::wasSetByUser(options::maxReplayTree__option_t) const { return d_holder->maxReplayTree__setByUser__; }
#line 158 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> const options::pbRewrites__option_t::type& Options::operator[](options::pbRewrites__option_t) const { return d_holder->pbRewrites; }
#line 158 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> bool Options::wasSetByUser(options::pbRewrites__option_t) const { return d_holder->pbRewrites__setByUser__; }
#line 161 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> const options::pbRewriteThreshold__option_t::type& Options::operator[](options::pbRewriteThreshold__option_t) const { return d_holder->pbRewriteThreshold; }
#line 161 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
template <> bool Options::wasSetByUser(options::pbRewriteThreshold__option_t) const { return d_holder->pbRewriteThreshold__setByUser__; }

#line 24 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/base_options_template.cpp"

namespace options {


#line 8 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
struct arithUnateLemmaMode__option_t arithUnateLemmaMode;
#line 11 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
struct arithPropagationMode__option_t arithPropagationMode;
#line 18 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
struct arithHeuristicPivots__option_t arithHeuristicPivots;
#line 25 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
struct arithStandardCheckVarOrderPivots__option_t arithStandardCheckVarOrderPivots;
#line 28 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
struct arithErrorSelectionRule__option_t arithErrorSelectionRule;
#line 32 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
struct arithSimplexCheckPeriod__option_t arithSimplexCheckPeriod;
#line 39 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
struct arithPivotThreshold__option_t arithPivotThreshold;
#line 42 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
struct arithPropagateMaxLength__option_t arithPropagateMaxLength;
#line 45 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
struct arithDioSolver__option_t arithDioSolver;
#line 50 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
struct arithRewriteEq__option_t arithRewriteEq;
#line 55 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
struct arithMLTrick__option_t arithMLTrick;
#line 59 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
struct arithMLTrickSubstitutions__option_t arithMLTrickSubstitutions;
#line 62 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
struct doCutAllBounded__option_t doCutAllBounded;
#line 66 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
struct maxCutsInContext__option_t maxCutsInContext;
#line 69 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
struct revertArithModels__option_t revertArithModels;
#line 72 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
struct havePenalties__option_t havePenalties;
#line 76 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
struct useFC__option_t useFC;
#line 79 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
struct useSOI__option_t useSOI;
#line 82 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
struct restrictedPivots__option_t restrictedPivots;
#line 85 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
struct collectPivots__option_t collectPivots;
#line 88 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
struct useApprox__option_t useApprox;
#line 91 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
struct maxApproxDepth__option_t maxApproxDepth;
#line 94 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
struct exportDioDecompositions__option_t exportDioDecompositions;
#line 97 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
struct newProp__option_t newProp;
#line 100 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
struct arithPropAsLemmaLength__option_t arithPropAsLemmaLength;
#line 103 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
struct soiQuickExplain__option_t soiQuickExplain;
#line 106 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
struct rewriteDivk__option_t rewriteDivk;
#line 109 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
struct trySolveIntStandardEffort__option_t trySolveIntStandardEffort;
#line 112 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
struct replayFailureLemma__option_t replayFailureLemma;
#line 115 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
struct dioSolverTurns__option_t dioSolverTurns;
#line 118 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
struct rrTurns__option_t rrTurns;
#line 121 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
struct dioRepeat__option_t dioRepeat;
#line 124 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
struct replayEarlyCloseDepths__option_t replayEarlyCloseDepths;
#line 127 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
struct replayFailurePenalty__option_t replayFailurePenalty;
#line 130 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
struct replayNumericFailurePenalty__option_t replayNumericFailurePenalty;
#line 133 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
struct replayRejectCutSize__option_t replayRejectCutSize;
#line 136 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
struct lemmaRejectCutSize__option_t lemmaRejectCutSize;
#line 139 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
struct soiApproxMajorFailure__option_t soiApproxMajorFailure;
#line 142 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
struct soiApproxMajorFailurePen__option_t soiApproxMajorFailurePen;
#line 145 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
struct soiApproxMinorFailure__option_t soiApproxMinorFailure;
#line 148 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
struct soiApproxMinorFailurePen__option_t soiApproxMinorFailurePen;
#line 151 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
struct ppAssertMaxSubSize__option_t ppAssertMaxSubSize;
#line 154 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
struct maxReplayTree__option_t maxReplayTree;
#line 158 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
struct pbRewrites__option_t pbRewrites;
#line 161 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/arith/options"
struct pbRewriteThreshold__option_t pbRewriteThreshold;

#line 30 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/base_options_template.cpp"

}/* CVC4::options namespace */

}/* CVC4 namespace */
