/*********************                                                        */
/** options.cpp
 **
 ** Copyright 2011-2014  New York University and The University of Iowa,
 ** and as below.
 **
 ** This file automatically generated by:
 **
 **     /home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/mkoptions /home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/base_options_template.cpp ../theory/quantifiers/options.cpp
 **
 ** for the CVC4 project.
 **/

/* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT ! */
/* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT ! */
/* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT ! */
/* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT ! */
/* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT ! */
/* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT ! */

/* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT ! */
/* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT ! */
/* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT ! */
/* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT ! */
/* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT ! */
/* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT ! */

/* Edit the template file instead.                     */

/*********************                                                        */
/*! \file base_options_template.cpp
 ** \verbatim
 ** Original author: Morgan Deters
 ** Major contributors: none
 ** Minor contributors (to current version): none
 ** This file is part of the CVC4 project.
 ** Copyright (c) 2009-2014  New York University and The University of Iowa
 ** See the file COPYING in the top-level source directory for licensing
 ** information.\endverbatim
 **
 ** \brief Contains code for handling command-line options.
 **
 ** Contains code for handling command-line options
 **/

#include "options/options_holder.h"

namespace CVC4 {


#line 11 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
template <> const options::miniscopeQuant__option_t::type& Options::operator[](options::miniscopeQuant__option_t) const { return d_holder->miniscopeQuant; }
#line 11 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
template <> bool Options::wasSetByUser(options::miniscopeQuant__option_t) const { return d_holder->miniscopeQuant__setByUser__; }
#line 17 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
template <> const options::miniscopeQuantFreeVar__option_t::type& Options::operator[](options::miniscopeQuantFreeVar__option_t) const { return d_holder->miniscopeQuantFreeVar; }
#line 17 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
template <> bool Options::wasSetByUser(options::miniscopeQuantFreeVar__option_t) const { return d_holder->miniscopeQuantFreeVar__setByUser__; }
#line 21 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
template <> const options::prenexQuant__option_t::type& Options::operator[](options::prenexQuant__option_t) const { return d_holder->prenexQuant; }
#line 21 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
template <> bool Options::wasSetByUser(options::prenexQuant__option_t) const { return d_holder->prenexQuant__setByUser__; }
#line 27 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
template <> const options::varElimQuant__option_t::type& Options::operator[](options::varElimQuant__option_t) const { return d_holder->varElimQuant; }
#line 27 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
template <> bool Options::wasSetByUser(options::varElimQuant__option_t) const { return d_holder->varElimQuant__setByUser__; }
#line 30 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
template <> const options::simpleIteLiftQuant__option_t::type& Options::operator[](options::simpleIteLiftQuant__option_t) const { return d_holder->simpleIteLiftQuant; }
#line 30 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
template <> bool Options::wasSetByUser(options::simpleIteLiftQuant__option_t) const { return d_holder->simpleIteLiftQuant__setByUser__; }
#line 34 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
template <> const options::cnfQuant__option_t::type& Options::operator[](options::cnfQuant__option_t) const { return d_holder->cnfQuant; }
#line 34 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
template <> bool Options::wasSetByUser(options::cnfQuant__option_t) const { return d_holder->cnfQuant__setByUser__; }
#line 37 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
template <> const options::nnfQuant__option_t::type& Options::operator[](options::nnfQuant__option_t) const { return d_holder->nnfQuant; }
#line 37 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
template <> bool Options::wasSetByUser(options::nnfQuant__option_t) const { return d_holder->nnfQuant__setByUser__; }
#line 40 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
template <> const options::clauseSplit__option_t::type& Options::operator[](options::clauseSplit__option_t) const { return d_holder->clauseSplit; }
#line 40 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
template <> bool Options::wasSetByUser(options::clauseSplit__option_t) const { return d_holder->clauseSplit__setByUser__; }
#line 46 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
template <> void Options::set(options::preSkolemQuant__option_t, const options::preSkolemQuant__option_t::type& x) { d_holder->preSkolemQuant = x; }
#line 46 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
template <> const options::preSkolemQuant__option_t::type& Options::operator[](options::preSkolemQuant__option_t) const { return d_holder->preSkolemQuant; }
#line 46 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
template <> bool Options::wasSetByUser(options::preSkolemQuant__option_t) const { return d_holder->preSkolemQuant__setByUser__; }
#line 49 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
template <> const options::aggressiveMiniscopeQuant__option_t::type& Options::operator[](options::aggressiveMiniscopeQuant__option_t) const { return d_holder->aggressiveMiniscopeQuant; }
#line 49 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
template <> bool Options::wasSetByUser(options::aggressiveMiniscopeQuant__option_t) const { return d_holder->aggressiveMiniscopeQuant__setByUser__; }
#line 52 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
template <> const options::macrosQuant__option_t::type& Options::operator[](options::macrosQuant__option_t) const { return d_holder->macrosQuant; }
#line 52 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
template <> bool Options::wasSetByUser(options::macrosQuant__option_t) const { return d_holder->macrosQuant__setByUser__; }
#line 55 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
template <> const options::foPropQuant__option_t::type& Options::operator[](options::foPropQuant__option_t) const { return d_holder->foPropQuant; }
#line 55 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
template <> bool Options::wasSetByUser(options::foPropQuant__option_t) const { return d_holder->foPropQuant__setByUser__; }
#line 59 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
template <> const options::smartTriggers__option_t::type& Options::operator[](options::smartTriggers__option_t) const { return d_holder->smartTriggers; }
#line 59 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
template <> bool Options::wasSetByUser(options::smartTriggers__option_t) const { return d_holder->smartTriggers__setByUser__; }
#line 62 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
template <> const options::relevantTriggers__option_t::type& Options::operator[](options::relevantTriggers__option_t) const { return d_holder->relevantTriggers; }
#line 62 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
template <> bool Options::wasSetByUser(options::relevantTriggers__option_t) const { return d_holder->relevantTriggers__setByUser__; }
#line 64 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
template <> const options::relationalTriggers__option_t::type& Options::operator[](options::relationalTriggers__option_t) const { return d_holder->relationalTriggers; }
#line 64 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
template <> bool Options::wasSetByUser(options::relationalTriggers__option_t) const { return d_holder->relationalTriggers__setByUser__; }
#line 68 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
template <> const options::registerQuantBodyTerms__option_t::type& Options::operator[](options::registerQuantBodyTerms__option_t) const { return d_holder->registerQuantBodyTerms; }
#line 68 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
template <> bool Options::wasSetByUser(options::registerQuantBodyTerms__option_t) const { return d_holder->registerQuantBodyTerms__setByUser__; }
#line 71 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
template <> void Options::set(options::instWhenMode__option_t, const options::instWhenMode__option_t::type& x) { d_holder->instWhenMode = x; }
#line 71 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
template <> const options::instWhenMode__option_t::type& Options::operator[](options::instWhenMode__option_t) const { return d_holder->instWhenMode; }
#line 71 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
template <> bool Options::wasSetByUser(options::instWhenMode__option_t) const { return d_holder->instWhenMode__setByUser__; }
#line 73 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
template <> const options::instMaxLevel__option_t::type& Options::operator[](options::instMaxLevel__option_t) const { return d_holder->instMaxLevel; }
#line 73 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
template <> bool Options::wasSetByUser(options::instMaxLevel__option_t) const { return d_holder->instMaxLevel__setByUser__; }
#line 76 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
template <> const options::eagerInstQuant__option_t::type& Options::operator[](options::eagerInstQuant__option_t) const { return d_holder->eagerInstQuant; }
#line 76 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
template <> bool Options::wasSetByUser(options::eagerInstQuant__option_t) const { return d_holder->eagerInstQuant__setByUser__; }
#line 79 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
template <> const options::fullSaturateQuant__option_t::type& Options::operator[](options::fullSaturateQuant__option_t) const { return d_holder->fullSaturateQuant; }
#line 79 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
template <> bool Options::wasSetByUser(options::fullSaturateQuant__option_t) const { return d_holder->fullSaturateQuant__setByUser__; }
#line 82 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
template <> const options::literalMatchMode__option_t::type& Options::operator[](options::literalMatchMode__option_t) const { return d_holder->literalMatchMode; }
#line 82 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
template <> bool Options::wasSetByUser(options::literalMatchMode__option_t) const { return d_holder->literalMatchMode__setByUser__; }
#line 85 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
template <> void Options::set(options::cbqi__option_t, const options::cbqi__option_t::type& x) { d_holder->cbqi = x; }
#line 85 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
template <> const options::cbqi__option_t::type& Options::operator[](options::cbqi__option_t) const { return d_holder->cbqi; }
#line 85 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
template <> bool Options::wasSetByUser(options::cbqi__option_t) const { return d_holder->cbqi__setByUser__; }
#line 88 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
template <> const options::recurseCbqi__option_t::type& Options::operator[](options::recurseCbqi__option_t) const { return d_holder->recurseCbqi; }
#line 88 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
template <> bool Options::wasSetByUser(options::recurseCbqi__option_t) const { return d_holder->recurseCbqi__setByUser__; }
#line 91 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
template <> const options::userPatternsQuant__option_t::type& Options::operator[](options::userPatternsQuant__option_t) const { return d_holder->userPatternsQuant; }
#line 91 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
template <> bool Options::wasSetByUser(options::userPatternsQuant__option_t) const { return d_holder->userPatternsQuant__setByUser__; }
#line 94 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
template <> const options::flipDecision__option_t::type& Options::operator[](options::flipDecision__option_t) const { return d_holder->flipDecision; }
#line 94 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
template <> bool Options::wasSetByUser(options::flipDecision__option_t) const { return d_holder->flipDecision__setByUser__; }
#line 97 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
template <> const options::internalReps__option_t::type& Options::operator[](options::internalReps__option_t) const { return d_holder->internalReps; }
#line 97 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
template <> bool Options::wasSetByUser(options::internalReps__option_t) const { return d_holder->internalReps__setByUser__; }
#line 100 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
template <> void Options::set(options::finiteModelFind__option_t, const options::finiteModelFind__option_t::type& x) { d_holder->finiteModelFind = x; }
#line 100 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
template <> const options::finiteModelFind__option_t::type& Options::operator[](options::finiteModelFind__option_t) const { return d_holder->finiteModelFind; }
#line 100 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
template <> bool Options::wasSetByUser(options::finiteModelFind__option_t) const { return d_holder->finiteModelFind__setByUser__; }
#line 103 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
template <> void Options::set(options::mbqiMode__option_t, const options::mbqiMode__option_t::type& x) { d_holder->mbqiMode = x; }
#line 103 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
template <> const options::mbqiMode__option_t::type& Options::operator[](options::mbqiMode__option_t) const { return d_holder->mbqiMode; }
#line 103 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
template <> bool Options::wasSetByUser(options::mbqiMode__option_t) const { return d_holder->mbqiMode__setByUser__; }
#line 105 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
template <> const options::fmfOneInstPerRound__option_t::type& Options::operator[](options::fmfOneInstPerRound__option_t) const { return d_holder->fmfOneInstPerRound; }
#line 105 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
template <> bool Options::wasSetByUser(options::fmfOneInstPerRound__option_t) const { return d_holder->fmfOneInstPerRound__setByUser__; }
#line 107 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
template <> const options::fmfOneQuantPerRound__option_t::type& Options::operator[](options::fmfOneQuantPerRound__option_t) const { return d_holder->fmfOneQuantPerRound; }
#line 107 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
template <> bool Options::wasSetByUser(options::fmfOneQuantPerRound__option_t) const { return d_holder->fmfOneQuantPerRound__setByUser__; }
#line 110 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
template <> const options::fmfInstEngine__option_t::type& Options::operator[](options::fmfInstEngine__option_t) const { return d_holder->fmfInstEngine; }
#line 110 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
template <> bool Options::wasSetByUser(options::fmfInstEngine__option_t) const { return d_holder->fmfInstEngine__setByUser__; }
#line 112 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
template <> const options::fmfInstGen__option_t::type& Options::operator[](options::fmfInstGen__option_t) const { return d_holder->fmfInstGen; }
#line 112 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
template <> bool Options::wasSetByUser(options::fmfInstGen__option_t) const { return d_holder->fmfInstGen__setByUser__; }
#line 114 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
template <> const options::fmfInstGenOneQuantPerRound__option_t::type& Options::operator[](options::fmfInstGenOneQuantPerRound__option_t) const { return d_holder->fmfInstGenOneQuantPerRound; }
#line 114 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
template <> bool Options::wasSetByUser(options::fmfInstGenOneQuantPerRound__option_t) const { return d_holder->fmfInstGenOneQuantPerRound__setByUser__; }
#line 116 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
template <> const options::fmfFreshDistConst__option_t::type& Options::operator[](options::fmfFreshDistConst__option_t) const { return d_holder->fmfFreshDistConst; }
#line 116 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
template <> bool Options::wasSetByUser(options::fmfFreshDistConst__option_t) const { return d_holder->fmfFreshDistConst__setByUser__; }
#line 118 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
template <> const options::fmfFmcSimple__option_t::type& Options::operator[](options::fmfFmcSimple__option_t) const { return d_holder->fmfFmcSimple; }
#line 118 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
template <> bool Options::wasSetByUser(options::fmfFmcSimple__option_t) const { return d_holder->fmfFmcSimple__setByUser__; }
#line 120 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
template <> void Options::set(options::fmfBoundInt__option_t, const options::fmfBoundInt__option_t::type& x) { d_holder->fmfBoundInt = x; }
#line 120 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
template <> const options::fmfBoundInt__option_t::type& Options::operator[](options::fmfBoundInt__option_t) const { return d_holder->fmfBoundInt; }
#line 120 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
template <> bool Options::wasSetByUser(options::fmfBoundInt__option_t) const { return d_holder->fmfBoundInt__setByUser__; }
#line 122 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
template <> void Options::set(options::fmfBoundIntLazy__option_t, const options::fmfBoundIntLazy__option_t::type& x) { d_holder->fmfBoundIntLazy = x; }
#line 122 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
template <> const options::fmfBoundIntLazy__option_t::type& Options::operator[](options::fmfBoundIntLazy__option_t) const { return d_holder->fmfBoundIntLazy; }
#line 122 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
template <> bool Options::wasSetByUser(options::fmfBoundIntLazy__option_t) const { return d_holder->fmfBoundIntLazy__setByUser__; }
#line 125 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
template <> const options::axiomInstMode__option_t::type& Options::operator[](options::axiomInstMode__option_t) const { return d_holder->axiomInstMode; }
#line 125 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
template <> bool Options::wasSetByUser(options::axiomInstMode__option_t) const { return d_holder->axiomInstMode__setByUser__; }
#line 128 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
template <> void Options::set(options::quantConflictFind__option_t, const options::quantConflictFind__option_t::type& x) { d_holder->quantConflictFind = x; }
#line 128 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
template <> const options::quantConflictFind__option_t::type& Options::operator[](options::quantConflictFind__option_t) const { return d_holder->quantConflictFind; }
#line 128 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
template <> bool Options::wasSetByUser(options::quantConflictFind__option_t) const { return d_holder->quantConflictFind__setByUser__; }
#line 130 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
template <> const options::qcfMode__option_t::type& Options::operator[](options::qcfMode__option_t) const { return d_holder->qcfMode; }
#line 130 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
template <> bool Options::wasSetByUser(options::qcfMode__option_t) const { return d_holder->qcfMode__setByUser__; }
#line 132 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
template <> const options::qcfWhenMode__option_t::type& Options::operator[](options::qcfWhenMode__option_t) const { return d_holder->qcfWhenMode; }
#line 132 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
template <> bool Options::wasSetByUser(options::qcfWhenMode__option_t) const { return d_holder->qcfWhenMode__setByUser__; }
#line 134 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
template <> void Options::set(options::qcfTConstraint__option_t, const options::qcfTConstraint__option_t::type& x) { d_holder->qcfTConstraint = x; }
#line 134 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
template <> const options::qcfTConstraint__option_t::type& Options::operator[](options::qcfTConstraint__option_t) const { return d_holder->qcfTConstraint; }
#line 134 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
template <> bool Options::wasSetByUser(options::qcfTConstraint__option_t) const { return d_holder->qcfTConstraint__setByUser__; }
#line 137 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
template <> const options::quantRewriteRules__option_t::type& Options::operator[](options::quantRewriteRules__option_t) const { return d_holder->quantRewriteRules; }
#line 137 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
template <> bool Options::wasSetByUser(options::quantRewriteRules__option_t) const { return d_holder->quantRewriteRules__setByUser__; }
#line 139 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
template <> const options::rrOneInstPerRound__option_t::type& Options::operator[](options::rrOneInstPerRound__option_t) const { return d_holder->rrOneInstPerRound; }
#line 139 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
template <> bool Options::wasSetByUser(options::rrOneInstPerRound__option_t) const { return d_holder->rrOneInstPerRound__setByUser__; }
#line 142 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
template <> const options::dtStcInduction__option_t::type& Options::operator[](options::dtStcInduction__option_t) const { return d_holder->dtStcInduction; }
#line 142 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
template <> bool Options::wasSetByUser(options::dtStcInduction__option_t) const { return d_holder->dtStcInduction__setByUser__; }

#line 24 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/base_options_template.cpp"

namespace options {


#line 11 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
struct miniscopeQuant__option_t miniscopeQuant;
#line 17 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
struct miniscopeQuantFreeVar__option_t miniscopeQuantFreeVar;
#line 21 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
struct prenexQuant__option_t prenexQuant;
#line 27 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
struct varElimQuant__option_t varElimQuant;
#line 30 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
struct simpleIteLiftQuant__option_t simpleIteLiftQuant;
#line 34 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
struct cnfQuant__option_t cnfQuant;
#line 37 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
struct nnfQuant__option_t nnfQuant;
#line 40 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
struct clauseSplit__option_t clauseSplit;
#line 46 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
struct preSkolemQuant__option_t preSkolemQuant;
#line 49 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
struct aggressiveMiniscopeQuant__option_t aggressiveMiniscopeQuant;
#line 52 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
struct macrosQuant__option_t macrosQuant;
#line 55 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
struct foPropQuant__option_t foPropQuant;
#line 59 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
struct smartTriggers__option_t smartTriggers;
#line 62 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
struct relevantTriggers__option_t relevantTriggers;
#line 64 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
struct relationalTriggers__option_t relationalTriggers;
#line 68 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
struct registerQuantBodyTerms__option_t registerQuantBodyTerms;
#line 71 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
struct instWhenMode__option_t instWhenMode;
#line 73 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
struct instMaxLevel__option_t instMaxLevel;
#line 76 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
struct eagerInstQuant__option_t eagerInstQuant;
#line 79 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
struct fullSaturateQuant__option_t fullSaturateQuant;
#line 82 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
struct literalMatchMode__option_t literalMatchMode;
#line 85 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
struct cbqi__option_t cbqi;
#line 88 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
struct recurseCbqi__option_t recurseCbqi;
#line 91 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
struct userPatternsQuant__option_t userPatternsQuant;
#line 94 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
struct flipDecision__option_t flipDecision;
#line 97 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
struct internalReps__option_t internalReps;
#line 100 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
struct finiteModelFind__option_t finiteModelFind;
#line 103 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
struct mbqiMode__option_t mbqiMode;
#line 105 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
struct fmfOneInstPerRound__option_t fmfOneInstPerRound;
#line 107 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
struct fmfOneQuantPerRound__option_t fmfOneQuantPerRound;
#line 110 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
struct fmfInstEngine__option_t fmfInstEngine;
#line 112 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
struct fmfInstGen__option_t fmfInstGen;
#line 114 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
struct fmfInstGenOneQuantPerRound__option_t fmfInstGenOneQuantPerRound;
#line 116 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
struct fmfFreshDistConst__option_t fmfFreshDistConst;
#line 118 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
struct fmfFmcSimple__option_t fmfFmcSimple;
#line 120 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
struct fmfBoundInt__option_t fmfBoundInt;
#line 122 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
struct fmfBoundIntLazy__option_t fmfBoundIntLazy;
#line 125 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
struct axiomInstMode__option_t axiomInstMode;
#line 128 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
struct quantConflictFind__option_t quantConflictFind;
#line 130 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
struct qcfMode__option_t qcfMode;
#line 132 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
struct qcfWhenMode__option_t qcfWhenMode;
#line 134 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
struct qcfTConstraint__option_t qcfTConstraint;
#line 137 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
struct quantRewriteRules__option_t quantRewriteRules;
#line 139 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
struct rrOneInstPerRound__option_t rrOneInstPerRound;
#line 142 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/../theory/quantifiers/options"
struct dtStcInduction__option_t dtStcInduction;

#line 30 "/home/mdeters/cvc4/builds/x86_64-unknown-linux-gnu/production/../../../src/options/base_options_template.cpp"

}/* CVC4::options namespace */

}/* CVC4 namespace */
